name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Configure API Key
        env:
          API_KEY: ${{ secrets.API_KEY }} 
        run: |
          echo "API_KEY=$API_KEY" >> $GITHUB_ENV

      - name: Build APK (Debug)
        run: ./gradlew assembleDebug
        env:
          API_KEY: ${{ secrets.API_KEY }} 
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
